import Head from "next/head";

import Barral from "../components/Barral";
import Footer from "../components/Footer";
import FooterEnd from "../components/FooterEnd";
import Header from "../components/Header";
import ProductFeed from "../components/ProductFeed";
import styles from "../styles/Home.module.css";

export default function Home({ products }) {
  const topTo = () => {
    window.scroll({
      top: 0,
      left: 0,
      behavior: "smooth",
    });
  };
  console.log(products);
  return (
    <div className="bg-gray-100 ">
      <Head>
        <title>Amazon 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="max-w-screen-2xl mx-auto">
        <Barral />

        <ProductFeed products={products} />
      </main>

      <div className="text-center bg-[#0d193ad7] text-white hover:opacity-90 py-3 cursor-pointer">
        <span onClick={topTo}>Back to top</span>
      </div>

      <div className="">
        <Footer />
      </div>
      <div className="">
        <FooterEnd />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (response) => response.json()
  );
  return {
    props: {
      products,
    },
  };
}
